/**
 * VeriGuide REST API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@veriguide.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServerValidation {
    data1?: string;
    data2?: string;
    failedMessage?: string;
    isFailed?: boolean;
}
